version: '3.9'

services:
  db:
    container_name: gallery_db
    restart: always
    env_file: .env
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_USER: postgres
      POSTGRES_DB: dev
  app:
    container_name: gallery_api
    restart: always
    build: .
    env_file: .env
    # networks:
    #   - default
    ports:
      - 3333:3333
      - 5555:5555
    depends_on:
      - db
    command: >
      sh -c "yarn && yarn prisma migrate dev && yarn build && yarn start"